import React from 'react';

const fallacies = [
  { name: "Abusive Ad Hominem", desc: "Attacking the character of an opponent rather than their argument.", example: "You're just a fool, so your theory on economics must be wrong." },
  { name: "Ad Hominem", desc: "Attacking the person instead of the argument.", example: "Why should we listen to a thief's ideas on politics?" },
  { name: "Anecdotal Fallacy", desc: "Using personal experience or isolated examples instead of sound arguments.", example: "My grandfather smoked 40 a day and lived to 100, so smoking isn't bad." },
  { name: "Appeal to Anonymous Authority", desc: "Using an unidentified authority to justify a claim.", example: "They say that green tea cures all ailments." },
  { name: "Appeal to Antiquity", desc: "Assuming something is better because it is old.", example: "We have practiced this for centuries; it must be the best way." },
  { name: "Appeal to Authority", desc: "Claiming a statement is true because an authority said so.", example: "My doctor said I should only eat kale, so it's the only healthy food." },
  { name: "Appeal to Belief", desc: "Stating that because many people believe something, it must be true.", example: "Millions of people believe in ghosts; therefore, ghosts exist." },
  { name: "Appeal to Common Sense", desc: "Assuming a claim is true because it seems like 'common sense'.", example: "It's just common sense that you can't trust robots." },
  { name: "Appeal to Consequences", desc: "Judging an argument based on the desirability of its outcomes.", example: "Global warming can't be real because if it were, we'd have to change our lifestyles." },
  { name: "Appeal to Emotion", desc: "Manipulating an emotional response in place of a valid argument.", example: "Think of the children! We must pass this law immediately." },
  { name: "Appeal to Faith", desc: "Using faith as the sole justification for a claim.", example: "I have faith that the sun will turn purple tomorrow." },
  { name: "Appeal to False Authority", desc: "Citing an authority who is not an expert on the subject.", example: "That famous actor said this medicine works, so it must." },
  { name: "Appeal to Fear", desc: "Using fear to support an argument.", example: "If you don't vote for me, the economy will collapse." },
  { name: "Appeal to Flattery", desc: "Using excessive praise to win support for an argument.", example: "Someone as intelligent as you surely sees that I am right." },
  { name: "Appeal to Force", desc: "Using threats or coercion to win an argument.", example: "Agree with me or lose your job." },
  { name: "Appeal to Hypocrisy", desc: "Rejecting an argument because the speaker fails to act consistently with it.", example: "You tell me to exercise, but you sit on the couch all day." },
  { name: "Appeal to Ignorance", desc: "Assuming a claim is true because it has not been proven false.", example: "No one has proven that aliens aren't here, so they are." },
  { name: "Appeal to Incredulity", desc: "Saying that because something is difficult to understand, it must be false.", example: "I can't imagine how life evolved, so it must have been designed." },
  { name: "Appeal to Intuition", desc: "Relying on a 'gut feeling' instead of evidence.", example: "I just feel in my gut that this stock will go up." },
  { name: "Appeal to Loyalty", desc: "Arguing that one should agree because of loyalty to a group.", example: "A true patriot would support this war regardless of the cost." },
  { name: "Appeal to Motive", desc: "Dismissing an argument by questioning the speaker's motives.", example: "You only want higher taxes because you're poor." },
  { name: "Appeal to Nature", desc: "Claiming that because something is 'natural' it is good/right.", example: "Herbal medicine is natural, so it's always better than chemicals." },
  { name: "Appeal to Novelty", desc: "Claiming something is better simply because it is new.", example: "This is the latest OS, so it's definitely the most efficient." },
  { name: "Appeal to Patriotism", desc: "Using nationalistic feelings to justify a claim.", example: "Supporting this bill is the only way to be a real citizen." },
  { name: "Appeal to Personal Experience", desc: "Using your own life events as universal truth.", example: "I was never robbed in this city, so it's completely safe." },
  { name: "Appeal to Pity", desc: "Trying to win support by exploiting feelings of pity or guilt.", example: "I spent three weeks on this essay; I deserve an A even if it's wrong." },
  { name: "Appeal to Popularity", desc: "Claiming a position is true because it is popular.", example: "Everyone is wearing these shoes, so they must be the best." },
  { name: "Appeal to Probability", desc: "Taking something for granted because it would probably be the case.", example: "It might rain, so it will definitely rain." },
  { name: "Appeal to Ridicule", desc: "Presenting the opponent's argument as absurd to dismiss it.", example: "So you think we came from monkeys? How ridiculous!" },
  { name: "Appeal to Spite", desc: "Using spite or bitterness to reject an argument.", example: "I hate that guy, so anything he says is wrong." },
  { name: "Appeal to the Majority", desc: "Claiming a claim is true because most people agree.", example: "The majority voted for him, so he's the best leader." },
  { name: "Appeal to Threat", desc: "Suggesting harm will come to those who disagree.", example: "You'll regret it if you don't follow my advice." },
  { name: "Appeal to Tradition", desc: "Assuming something is correct because it's been done for a long time.", example: "Our family has always farmed this way; it is the right way." },
  { name: "Availability Heuristic", desc: "Overestimating the importance of information that is easy to recall.", example: "Plane crashes are all over the news, so flying is deadly." },
  { name: "Bandwagon Fallacy", desc: "Following the crowd regardless of logic.", example: "All my friends are doing it, so it's fine." },
  { name: "Base Rate Fallacy", desc: "Ignoring general information in favor of specific details.", example: "The test is 99% accurate, so my positive result is 99% likely true." },
  { name: "Begging the Question", desc: "The conclusion is included in the premise.", example: "God exists because the Bible says so, and God wrote the Bible." },
  { name: "Biased Sample", desc: "Drawing a conclusion from a non-representative sample.", example: "I asked 100 sailors if they liked the sea; 100% of humans love the sea." },
  { name: "Causal Oversimplification", desc: "Assuming one single cause for a complex event.", example: "The school shooting happened because of video games." },
  { name: "Causal Reductionism", desc: "Reducing a complex set of causes to a single one.", example: "The economy crashed only because of interest rates." },
  { name: "Cherry Picking", desc: "Selecting only data that supports your claim.", example: "This study shows 1 person got better, ignore the 99 who got worse." },
  { name: "Circular Reasoning", desc: "The argument starts where it ends.", example: "The law is just because it is legal." },
  { name: "Circumstantial Ad Hominem", desc: "Attacking someone by citing their circumstances.", example: "You're a priest, so your arguments for morality are biased." },
  { name: "Complex Question", desc: "Asking a question with a built-in assumption.", example: "Have you stopped beating your wife yet?" },
  { name: "Composition Fallacy", desc: "Assuming what is true for a part is true for the whole.", example: "Every player on this team is a star, so the team is unbeatable." },
  { name: "Confirmation Bias", desc: "Seeking information that confirms existing beliefs.", example: "I only read news sites that agree with my politics." },
  { name: "Continuum Fallacy", desc: "Rejecting a distinction because it's not absolutely precise.", example: "Since there is no exact point a man becomes bald, the concept of baldness is useless." },
  { name: "Correlation Equals Causation", desc: "Assuming that because two things happen together, one caused the other.", example: "Ice cream sales and drownings rise together, so ice cream causes drowning." },
  { name: "Cum Hoc Ergo Propter Hoc", desc: "With this, therefore because of this.", example: "He wore red socks and won; the red socks caused the win." },
  { name: "Division Fallacy", desc: "Assuming what is true for the whole is true for every part.", example: "This company is great, so every employee must be great." },
  { name: "Fallacy Fallacy", desc: "Assuming a claim is false just because the argument for it was fallacious.", example: "You used a straw man, therefore your conclusion is definitely wrong." },
  { name: "False Analogy", desc: "Comparing two things that aren't actually alike in relevant ways.", example: "Employees are like nails; they need to be hit to work." },
  { name: "False Attribution", desc: "Citing an irrelevant, biased, or non-existent source.", example: "Einstein once said that I am the smartest person alive." },
  { name: "False Balance", desc: "Giving equal weight to two sides when one is clearly backed by evidence.", example: "Let's debate if the earth is round or flat for 30 minutes each." },
  { name: "False Cause", desc: "Incorrectly identifying the cause of an event.", example: "I broke a mirror and then tripped; the mirror caused the trip." },
  { name: "False Consensus Effect", desc: "Overestimating how much others agree with you.", example: "I think this movie is great, so surely everyone else does too." },
  { name: "False Dichotomy", desc: "Presenting only two options when more exist.", example: "Either you're with us, or you're with the terrorists." },
  { name: "False Dilemma", desc: "Similar to false dichotomy, limiting options artificially.", example: "Buy this car or walk for the rest of your life." },
  { name: "False Equivalence", desc: "Assuming two things are the same when they are not.", example: "Both apples and oranges are round, so they taste the same." },
  { name: "False Precision", desc: "Using overly exact numbers for inexact concepts.", example: "The statue is 500,003 years old (because I saw it 3 years ago and they said 500k)." },
  { name: "False Premise", desc: "An argument based on an incorrect starting assumption.", example: "All cats are invisible; I have a cat; therefore my cat is invisible." },
  { name: "False Representation", desc: "Misrepresenting someone's position to make it easier to attack.", example: "You said you liked dogs, so you must hate cats." },
  { name: "Faulty Generalization", desc: "Reaching a conclusion based on weak evidence.", example: "That dog bit me; all dogs are dangerous." },
  { name: "Genetic Fallacy", desc: "Judging something based on its origins rather than its current state.", example: "This idea came from a cult, so it must be bad." },
  { name: "Guilt by Association", desc: "Dismissing an argument because the speaker is associated with a disliked group.", example: "He’s friends with a criminal, so his moral advice is garbage." },
  { name: "Halo Effect", desc: "Letting overall impression of a person color judgment of specific traits.", example: "He's handsome, so he must be a kind person." },
  { name: "Hasty Generalization", desc: "Drawing a conclusion from a small sample size.", example: "I met two rude Parisians; everyone in Paris is rude." },
  { name: "Historian’s Fallacy", desc: "Judging historical figures by modern standards they couldn't have known.", example: "Those ancient people were stupid for not using antibiotics." },
  { name: "Horn Effect", desc: "Letting one negative trait color your entire perception of a person.", example: "He has a messy desk, so he's a terrible accountant." },
  { name: "Hot Hand Fallacy", desc: "Believing that a streak of luck will continue.", example: "I've won three times in a row, I'm 'hot' now." },
  { name: "Illusory Correlation", desc: "Perceiving a relationship where none exists.", example: "Every time I wash my car, it rains." },
  { name: "Incomplete Comparison", desc: "Comparing things without providing enough information.", example: "This battery lasts longer!" },
  { name: "Inconsistent Comparison", desc: "Using different criteria for different subjects in a comparison.", example: "Product A is cheaper than B, but Product B is prettier than C." },
  { name: "Loaded Question", desc: "A question that contains a controversial assumption.", example: "Why do you hate freedom?" },
  { name: "Masked Man Fallacy", desc: "Substitution of identical designators in a context where they are not interchangeable.", example: "I know who my father is. I don't know who the masked man is. Therefore, my father is not the masked man." },
  { name: "Middle Ground Fallacy", desc: "Assuming the truth lies exactly in the middle of two extremes.", example: "I say the sky is blue, he says it's red; it must be purple." },
  { name: "Moralistic Fallacy", desc: "Assuming something is false because it is morally undesirable.", example: "Cheating doesn't happen because it's wrong." },
  { name: "Naturalistic Fallacy", desc: "Assuming something is good because it exists in nature.", example: "Tigers eat meat, so humans should only eat meat." },
  { name: "Nirvana Fallacy", desc: "Rejecting a solution because it is not perfect.", example: "Seatbelts aren't 100% effective, so we shouldn't use them." },
  { name: "No True Scotsman", desc: "Protecting a generalization from counter-examples by changing the definition.", example: "No Scotsman puts sugar on porridge. My uncle does. Well, no *true* Scotsman does." },
  { name: "Non Sequitur", desc: "The conclusion does not follow from the premises.", example: "It's sunny out, so we should eat pasta." },
  { name: "Overgeneralization", desc: "Applying a specific rule to a general situation too broadly.", example: "One person lied to me; I can never trust anyone again." },
  { name: "Package Deal Fallacy", desc: "Assuming that because someone holds one belief, they hold a set of others.", example: "He's an environmentalist, so he must be a vegan." },
  { name: "Perfectionist Fallacy", desc: "Assuming a task should be abandoned if it cannot be done perfectly.", example: "I missed one day of the gym, so my whole diet is ruined." },
  { name: "Personal Incredulity", desc: "Rejecting a claim because you find it hard to believe.", example: "I don't see how molecules can think, so neuroscience is fake." },
  { name: "Poisoning the Well", desc: "Discrediting an opponent before they even speak.", example: "Don't listen to anything he says; he's a known liar." },
  { name: "Post Hoc Ergo Propter Hoc", desc: "After this, therefore because of this.", example: "The rooster crowed and then the sun rose; the rooster caused the sunrise." },
  { name: "Prosecutor’s Fallacy", desc: "The error of statistical reasoning, typically in legal contexts.", example: "The DNA match is 1 in a million, so the defendant is 99.9999% likely guilty." },
  { name: "Red Herring", desc: "Introducing irrelevant information to distract from the main topic.", example: "Why talk about climate change when the economy is hurting?" },
  { name: "Regression Fallacy", desc: "Assuming a return to the mean is caused by an external action.", example: "I felt terrible, drank a juice, and got better (ignoring natural recovery)." },
  { name: "Regression to the Mean Fallacy", desc: "Ignoring natural fluctuations in data.", example: "The star athlete's second season was worse; it was the 'sophomore slump'." },
  { name: "Reification", desc: "Treating an abstract concept as if it were a physical reality.", example: "Nature hates a vacuum." },
  { name: "Relative Privation", desc: "Dismissing a problem because 'worse' problems exist.", example: "Don't complain about your leg, people are starving in other countries." },
  { name: "Retroactive Causation", desc: "The belief that future events can cause past events.", example: "I felt sick today because I'm going to get a cold on Friday." },
  { name: "Self-Sealing Argument", desc: "An argument that is structured so it cannot be proven false.", example: "Only the enlightened can see the truth." },
  { name: "Shifting the Burden of Proof", desc: "Demanding the opponent prove you wrong rather than proving your claim.", example: "Prove that I don't have an invisible dragon in my garage." },
  { name: "Slippery Slope", desc: "Claiming a small step will lead to a chain of catastrophic events.", example: "If we allow kids to choose their lunch, the world will end in chaos." },
  { name: "Special Pleading", desc: "Claiming an exception to a rule without justification.", example: "I'm psychic, but my powers don't work when skeptics are around." },
  { name: "Spotlight Fallacy", desc: "Assuming the media representation of a group is the whole group.", example: "I saw three news stories about corrupt politicians; all politicians are corrupt." },
  { name: "Straw Man", desc: "Misrepresenting an argument to make it easier to attack.", example: "You want to reduce military spending? You must want us to be defenseless!" },
  { name: "Suppressed Evidence", desc: "Intentionally leaving out data that contradicts a claim.", example: "This car is great! (Ignoring that the engine is missing)." },
  { name: "Sweeping Generalization", desc: "Applying a general rule to a specific case it doesn't fit.", example: "Cutting people is a crime; surgeons cut people; surgeons are criminals." },
  { name: "Texas Sharpshooter Fallacy", desc: "Finding patterns in data after the fact to support a claim.", example: "He shot a wall, then drew a bullseye around the cluster of holes." },
  { name: "Third Variable Fallacy", desc: "Ignoring a hidden factor that causes both A and B.", example: "Ice cream and shark attacks correlate because of heat (the third variable)." },
  { name: "Tu Quoque", desc: "Dismissing an argument because the speaker acts inconsistently.", example: "Why should I stop smoking? You smoke too!" },
  { name: "Undistributed Middle", desc: "A syllogistic error where the middle term is not distributed.", example: "All sharks are fish; all goldfish are fish; therefore all sharks are goldfish." },
  { name: "Unfalsifiable Claim", desc: "A claim that cannot be tested or proven wrong.", example: "Invisible unicorns are everywhere." },
  { name: "Weak Analogy", desc: "Using a comparison that is too slight to support a conclusion.", example: "Guns are like hammers; both are metal tools, so both should be unregulated." },
  { name: "Wishful Thinking", desc: "Assuming something is true because you want it to be.", example: "I really want this lottery ticket to win, so it will." },
  { name: "Zero-Sum Fallacy", desc: "Assuming that for one to gain, another must lose.", example: "If you get a raise, I must be getting less money." }
];

export default ({ onClose }: any) => (
  <div className="absolute inset-0 z-[120] bg-black/95 backdrop-blur-2xl flex flex-col p-6 animate-in fade-in duration-300">
    <div className="flex items-center justify-between border-b border-emerald-900/30 pb-4 mb-6">
      <h2 className="text-xl font-orbitron text-emerald-500 tracking-widest uppercase">Fallacy Registry</h2>
      <button onClick={onClose} className="p-3 border border-emerald-500 text-emerald-500 text-[10px] uppercase">Close_DB</button>
    </div>
    <div className="flex-1 overflow-y-auto custom-scrollbar space-y-4">
      {fallacies.map((f, i) => (
        <div key={i} className="p-4 border border-emerald-900/20 bg-emerald-950/5 rounded hover:border-emerald-500/30">
          <h3 className="text-emerald-400 font-orbitron text-[11px] uppercase">{f.name}</h3>
          <p className="text-[10px] text-emerald-700 leading-tight font-mono">{f.desc}</p>
          <div className="p-2 bg-black/40 border-l border-emerald-500/20 mt-2">
            <p className="text-[9px] text-emerald-900 italic font-mono">EX: {f.example}</p>
          </div>
        </div>
      ))}
    </div>
  </div>
);
